import { NewsSource, NewsCategory } from './types';

export const NEWS_SOURCES: NewsSource[] = [
  {
    id: 'reuters-world',
    name: 'Reuters World News',
    type: 'rss',
    url: 'https://feeds.reuters.com/reuters/worldNews',
    category: 'geopolitical',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 30,
  },
  {
    id: 'reuters-business',
    name: 'Reuters Business',
    type: 'rss',
    url: 'https://feeds.reuters.com/reuters/businessNews',
    category: 'stocks',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 30,
  },
  {
    id: 'reuters-technology',
    name: 'Reuters Technology',
    type: 'rss',
    url: 'https://feeds.reuters.com/reuters/technologyNews',
    category: 'stocks',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 30,
  },
  {
    id: 'bbc-world',
    name: 'BBC World News',
    type: 'rss',
    url: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    category: 'geopolitical',
    country: 'GB',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 30,
  },
  {
    id: 'bbc-business',
    name: 'BBC Business',
    type: 'rss',
    url: 'https://feeds.bbci.co.uk/news/business/rss.xml',
    category: 'stocks',
    country: 'GB',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 30,
  },
  {
    id: 'ap-news',
    name: 'Associated Press News',
    type: 'rss',
    url: 'https://feeds.apnews.com/rss/apf-topnews',
    category: 'geopolitical',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 30,
  },
  {
    id: 'ap-business',
    name: 'Associated Press Business',
    type: 'rss',
    url: 'https://feeds.apnews.com/rss/apf-business',
    category: 'stocks',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 30,
  },
  {
    id: 'ft-markets',
    name: 'Financial Times Markets',
    type: 'rss',
    url: 'https://www.ft.com/markets/rss',
    category: 'stocks',
    country: 'GB',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 30,
  },
  {
    id: 'wsj-markets',
    name: 'Wall Street Journal Markets',
    type: 'rss',
    url: 'https://feeds.a.dj.com/rss/RSSMarketsMain.xml',
    category: 'stocks',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 30,
  },
  {
    id: 'bloomberg-markets',
    name: 'Bloomberg Markets',
    type: 'rss',
    url: 'https://feeds.bloomberg.com/markets/news.rss',
    category: 'stocks',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 15,
  },
  {
    id: 'cnbc-markets',
    name: 'CNBC Markets',
    type: 'rss',
    url: 'https://www.cnbc.com/id/100003114/device/rss/rss.html',
    category: 'stocks',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 15,
  },
  {
    id: 'marketwatch',
    name: 'MarketWatch',
    type: 'rss',
    url: 'https://feeds.marketwatch.com/marketwatch/topstories/',
    category: 'stocks',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 15,
  },
  {
    id: 'investing-com-forex',
    name: 'Investing.com Forex',
    type: 'rss',
    url: 'https://www.investing.com/rss/news_285.rss',
    category: 'forex',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 15,
  },
  {
    id: 'fxstreet',
    name: 'FXStreet',
    type: 'rss',
    url: 'https://www.fxstreet.com/rss/news',
    category: 'forex',
    country: 'ES',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 15,
  },
  {
    id: 'dailyfx',
    name: 'DailyFX',
    type: 'rss',
    url: 'https://www.dailyfx.com/feeds/marketnews',
    category: 'forex',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 15,
  },
  {
    id: 'coindesk',
    name: 'CoinDesk',
    type: 'rss',
    url: 'https://www.coindesk.com/arc/outboundfeeds/rss/',
    category: 'crypto',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 15,
  },
  {
    id: 'cointelegraph',
    name: 'CoinTelegraph',
    type: 'rss',
    url: 'https://cointelegraph.com/rss',
    category: 'crypto',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 15,
  },
  {
    id: 'the-block',
    name: 'The Block',
    type: 'rss',
    url: 'https://www.theblock.co/rss.xml',
    category: 'crypto',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 15,
  },
  {
    id: 'decrypt',
    name: 'Decrypt',
    type: 'rss',
    url: 'https://decrypt.co/feed',
    category: 'crypto',
    country: 'US',
    official: true,
    attributionRequired: true,
    enabled: true,
    refreshMinutes: 15,
  },
];

export function getEnabledSources(): NewsSource[] {
  return NEWS_SOURCES.filter((source) => source.enabled);
}

export function getSourcesByCategory(category: NewsCategory): NewsSource[] {
  return NEWS_SOURCES.filter((source) => source.enabled && source.category === category);
}

export function getSourceById(id: string): NewsSource | undefined {
  return NEWS_SOURCES.find((source) => source.id === id);
}

export function getOfficialSources(): NewsSource[] {
  return NEWS_SOURCES.filter((source) => source.enabled && source.official);
}